AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  s3snstriggerthumbnail:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 10
      Role: 'arn:aws:iam::830644186520:role/service-role/s3-sns-trigger-thumbnail'
      RuntimePolicy:
        UpdateRuntimeOn: Auto
